name: DataMiner Deploy Only Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  CD:
    environment: production
    name: CD
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3

       - name: Skyline DataMiner Deploy Action
         uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
         with:
           # Stage deploy
           stage: All
           # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
           api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
           solution-path: ./AutomationScript.sln
           artifact-name: ${{ github.repository }} ${{ github.ref_name }}
           version: ${{ github.ref_name }}
           build-number: ${{ github.run_number }}
           
